### ISSUE TITLE
v4.6 compatiblity?

### ISSUE THREAD

**Issue by jamienovick** [veda-consulting/uk.co.vedaconsulting.payment.gocardlessdd#4]
Hey guys, whats the v4.6 status of this? We've done a few tests but had some issues. Have you looked into support? Any idea of time/costs involved?

J

**Comment by veda-consulting** [comment]
@jamienovick we've tested the all the Direct Debit extensions on 4.6, if you could raise any specific issues we can take a look.

**Comment by veda-consulting** [comment]
Closing
